### ISSUE TITLE
[Request]Data/Images +Script Extract/Repack tool for Senkou no Clarias (GIGA -new NeXAS engine archives)

### ISSUE THREAD

**Issue by tbhoang12** [AyamiKaze/GalgameNote#1]
Hi can you make tool for extract + repack Senkou no Clarias script / images /UI?https://vndb.org/v28309
 I used your NeXAS tool but it can only extract .pac file extension For example System.pac >> drop into your tool cmd window >> got System. pac_unpack folder (contains .PNG images for UI icons ,images of the game) + System.pac_INDEX (i don't know what to do next because there is no repack tool ?) .
Much thanks 4 your contribution to visual novel translation community o /
https://cdn.discordapp.com/attachments/308897786500481025/911682239060910150/Clarias_NeXAS_Unpack.jpg

![Clarias NeXAS Unpack](https://user-images.githubusercontent.com/76590480/142738950-9b8cf8f0-0420-48f6-a237-29a52c6b780e.jpg)
If you can please make tools for extract/repack not just .pac file ,but also .bin (script file extension ) and .dat (inside the .pac archive i saw these but don't know what is their role )
Also i noticed the old .pac file unpack and repack here in Fuwanovel ,did not works with the new eroge/gal game/ visual novels from GIGA (examples like AiKiss and Clarias, maybe  they used an updated version of NeXAS engine )
https://forums.fuwanovel.net/topic/17841-script-extraction-thread/?tab=comments#comment-453725

**Comment by AyamiKaze** [comment]
https://github.com/AyamiKaze/Niflheim/tree/master/NeXAS/BALDR_HEART

**Comment by AyamiKaze** [comment]
> https://github.com/AyamiKaze/Niflheim/tree/master/NeXAS/BALDR_HEART

for repack, just change some code in struct. These code also in unpack code. Check by yourself.

**Comment by tbhoang12** [comment]
> > https://github.com/AyamiKaze/Niflheim/tree/master/NeXAS/BALDR_HEART
> 
> for repack, just change some code in struct. These code also in unpack code. Check by yourself.

well here is the thing , i'm just a student who learned JP and i had to relied on Google TL to understand Chinese ,and also i don't know anything about coding /programming so i don't understand what you said about "change some code in struct" ???/ or how to download the github file in the link you gave me above 
**So if you have time in the future please considers making a easy to use and intuitive tool (without those complicated cmd commands!!)  to translate new visual novels from GIGA (like Clarias for example )**
There is a tool from another Chinese guy to pack and repack .pac files ,but i tried on Clarias and the newer visual novels from GIGA ,it just does not working .So that's why i have to go here asking you .
https://github.com/uyjulian/zbspac/releases/tag/v3.0.0

**Comment by AyamiKaze** [comment]
> 
[_giga_tools.zip](https://github.com/AyamiKaze/GalgameNote/files/7581254/_giga_tools.zip)
![test1](https://user-images.githubusercontent.com/47900658/142868388-d4d390ab-e894-486f-a0d3-ecd73d693d74.png)
![test2](https://user-images.githubusercontent.com/47900658/142868409-8bf454c0-f093-47d2-a844-62a6a76cf705.png)
tested.

**Comment by tbhoang12** [comment]
wow that was fast thank you !
You should post your tools and create a TL guide for people who wants to
translate GIGA games (in english) ,like this Russian guy .By doing so ,
maybe we will get more translation groups to translate their game (
official translation company can't buy all of the licenses to TL these
visual novels due to the cost of voice actors is increasing - they're also
working in Mobile games market in Japan and some China games too )
https://github.com/TesterTesterov/SLGSystemDataTool
I'm still waiting for Clarias F DLC , don't know if your tool will work or
not by that time when dev team update their game but let's wait and see :)
